"""empty message

Revision ID: 1562d3ffdb76
Revises: 474e2bb65507
Create Date: 2015-02-12 22:21:41.367195

"""

# revision identifiers, used by Alembic.
revision = '1562d3ffdb76'
down_revision = '474e2bb65507'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=256), nullable=True),
    sa.Column('body', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    ### end Alembic commands ###
