"""empty message

Revision ID: 1a7d10502e5a
Revises: 1562d3ffdb76
Create Date: 2015-02-12 23:43:33.434013

"""

# revision identifiers, used by Alembic.
revision = '1a7d10502e5a'
down_revision = '1562d3ffdb76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
