"""empty message

Revision ID: 1ae3600852d5
Revises: 580db389483a
Create Date: 2015-02-27 01:00:06.548821

"""

# revision identifiers, used by Alembic.
revision = '1ae3600852d5'
down_revision = '580db389483a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_show', sa.Column('nickname', sa.String(length=16), nullable=True))
    op.add_column('people_show', sa.Column('weibo_follow', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people_show', 'weibo_follow')
    op.drop_column('people_show', 'nickname')
    ### end Alembic commands ###
