"""empty message

Revision ID: 1edf592afa9f
Revises: 1202533f98f8
Create Date: 2015-04-06 15:05:04.600874

"""

# revision identifiers, used by Alembic.
revision = '1edf592afa9f'
down_revision = '1202533f98f8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('blog_category_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_category_id'], ['blog_category.id'], ),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], )
    )
    op.drop_constraint(u'blog_ibfk_1', 'blog', type_='foreignkey')
    op.drop_column(u'blog', 'category_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'blog', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'blog_ibfk_1', 'blog', 'blog_category', ['category_id'], ['id'])
    op.drop_table('blogs')
    ### end Alembic commands ###
