"""empty message

Revision ID: 26964f78ad5e
Revises: 522a197e6cc
Create Date: 2015-03-11 11:44:04.193399

"""

# revision identifiers, used by Alembic.
revision = '26964f78ad5e'
down_revision = '522a197e6cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('categories', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'categories')
    ### end Alembic commands ###
