"""empty message

Revision ID: 334c1283197a
Revises: 44e02d7d9f5
Create Date: 2015-02-14 17:39:30.785399

"""

# revision identifiers, used by Alembic.
revision = '334c1283197a'
down_revision = '44e02d7d9f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('href', sa.String(length=128), nullable=True))
    op.add_column('post', sa.Column('sticky', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('youku_vid', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'youku_vid')
    op.drop_column('post', 'sticky')
    op.drop_column('post', 'href')
    ### end Alembic commands ###
