"""empty message

Revision ID: 361e2ab1249d
Revises: 230b1696b9e7
Create Date: 2015-02-08 00:12:36.671118

"""

# revision identifiers, used by Alembic.
revision = '361e2ab1249d'
down_revision = '230b1696b9e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('role_id', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'role_id')
    op.drop_table('role')
    ### end Alembic commands ###
