"""empty message

Revision ID: 36fe1bec2548
Revises: 361e2ab1249d
Create Date: 2015-02-08 00:20:39.347242

"""

# revision identifiers, used by Alembic.
revision = '36fe1bec2548'
down_revision = '361e2ab1249d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
