"""empty message

Revision ID: 4385156c2525
Revises: 26964f78ad5e
Create Date: 2015-03-11 16:02:46.344714

"""

# revision identifiers, used by Alembic.
revision = '4385156c2525'
down_revision = '26964f78ad5e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'blog_category', ['category'], ['id'])
    op.drop_column('blog', 'categories')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('categories', mysql.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'category')
    ### end Alembic commands ###
