"""empty message

Revision ID: 44e02d7d9f5
Revises: 5a76bb622dd
Create Date: 2015-02-14 02:46:12.899128

"""

# revision identifiers, used by Alembic.
revision = '44e02d7d9f5'
down_revision = '5a76bb622dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_show', sa.Column('live_src', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people_show', 'live_src')
    ### end Alembic commands ###
