"""empty message

Revision ID: 4c673b4c0baa
Revises: 1a7d10502e5a
Create Date: 2015-02-12 23:46:45.902842

"""

# revision identifiers, used by Alembic.
revision = '4c673b4c0baa'
down_revision = '1a7d10502e5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=256), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    ### end Alembic commands ###
