"""empty message

Revision ID: 4deb37e956a9
Revises: 334c1283197a
Create Date: 2015-02-15 00:19:49.612186

"""

# revision identifiers, used by Alembic.
revision = '4deb37e956a9'
down_revision = '334c1283197a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weibo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.Column('images', sa.String(length=512), nullable=True),
    sa.Column('href', sa.String(length=128), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people_show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weibo')
    ### end Alembic commands ###
