"""empty message

Revision ID: 522a197e6cc
Revises: 1ae3600852d5
Create Date: 2015-03-10 10:56:29.358692

"""

# revision identifiers, used by Alembic.
revision = '522a197e6cc'
down_revision = '1ae3600852d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    ### end Alembic commands ###
