"""empty message

Revision ID: 580db389483a
Revises: 4deb37e956a9
Create Date: 2015-02-15 22:39:05.122417

"""

# revision identifiers, used by Alembic.
revision = '580db389483a'
down_revision = '4deb37e956a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=80), nullable=True),
    sa.Column('href', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people_show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_image')
    ### end Alembic commands ###
