"""empty message

Revision ID: 5a76bb622dd
Revises: c01a3266eae
Create Date: 2015-02-14 00:27:30.195859

"""

# revision identifiers, used by Alembic.
revision = '5a76bb622dd'
down_revision = 'c01a3266eae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('images', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'images')
    ### end Alembic commands ###
